### ISSUE TITLE
Unexpected keyword argument "closed" for "Interval"

### ISSUE THREAD

**Issue by lmar76** [VirtusLab/pandas-stubs#123]
As indicated in the official Pandas [documentation](https://pandas.pydata.org/docs/reference/api/pandas.Interval.html), `pandas.Interval` constructor accepts parameters:
- `left`
- `right`
- `closed`

The following code:

```python
import pandas

def to_interval(left: int, right: int) -> pandas.Interval:
    return pandas.Interval(left, right, closed='both')

if __name__ == '__main__':
    print(to_interval(1, 2))
```

can be successfully executed:
```
$ python main.py 
[1, 2]
```

however mypy trace the errors:
```
$ mypy main.py 
main.py:4: error: Too many arguments for "Interval"
main.py:4: error: Unexpected keyword argument "closed" for "Interval"
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by zkrolikowski-vl** [comment]
Hi @lmar76. Thanks for reporting.

Looks like we haven't had good typing coverage of Interval because it was declared in a .pyx format.

I've created a PR to amend. It'll be merged soon and then a new release will be made: https://github.com/VirtusLab/pandas-stubs/pull/124

Thanks again for finding this!

**Comment by zkrolikowski-vl** [comment]
Version [1.2.0.40](https://pypi.org/project/pandas-stubs/1.2.0.40/) has been released. Feel free to download and run mypy again.
