### ISSUE TITLE
pandas.DataFrame.merge signature - 'suffixes' parameter - expected type not compliant with documentation

### ISSUE THREAD

**Issue by PatrickBourdon** [VirtusLab/pandas-stubs#137]
**Environment:**
  - Pandas-stubs: 1.2.0.45
  - Dev environment: VSCode 1.63.2, Pylance v2022.1.3
  - Python: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
  - Platform: Windows-10-10.0.19042-SP0

**Issue:**
[Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html?highlight=merge#pandas-dataframe-merge) for the suffixes parameter says:  _Pass a value of None instead of a string to indicate that the column name from left or right should be left as-is, with no suffix. At least one of the values must not be None._

But the expected type is `tuple[str, str]`. Hence the type checker reports a problem with `None`.

![image](https://user-images.githubusercontent.com/78907421/151432841-71f64747-65c4-4767-9f4b-c3ae3f65f077.png)

Thank you for the great job.

**Comment by joannasendorek** [comment]
Hi @PatrickBourdon, thank you for reporting an issue. I have prepared the fix #141. 

I also noticed that it doesn't need to be a Tuple, it can be any iterable, of length 2. This would be very problematic however, because there is no way to ensure constant length for other iterables, so I will leave it to accept only tuples.
