### ISSUE TITLE
Is test_series:test_types_values incorrect?

### ISSUE THREAD

**Issue by Dr-Irv** [VirtusLab/pandas-stubs#142]
We're using the tests here with the Microsoft type stubs.  In `test_series.py`, you have:
```python
def test_types_values() -> None:
    n1: np.ndarray = pd.Series([1, 2, 3]).values
    n2: np.ndarray = pd.Series(list('aabc')).values
    n3: np.ndarray = pd.Series(list('aabc')).astype('category').values
    n4: np.ndarray = pd.Series(pd.date_range('20130101', periods=3, tz='US/Eastern')).values
```
The issue here is that `Series.values` can return a `np.ndarray` or an `ExtensionArray` .  Here's results of typing the 4 cases above:
```python
>>> import pandas as pd
>>> pd.__version__
'1.4.0'
>>> type(pd.Series([1, 2, 3]).values)
<class 'numpy.ndarray'>
>>> type( pd.Series(list('aabc')).values)
<class 'numpy.ndarray'>
>>> type(pd.Series(list('aabc')).astype('category').values)
<class 'pandas.core.arrays.categorical.Categorical'>
>>> type(pd.Series(pd.date_range('20130101', periods=3, tz='US/Eastern')).values
)
<class 'numpy.ndarray'>
```

So in your stubs and tests, for the `category` example, the test (and stubs) is incorrect, as it doesn't return a `np.ndarray`

And if you use the new string dtype, you have:
```python
>>> type(pd.Series(["abc", "def", "ghi"], dtype="string").values)
<class 'pandas.core.arrays.string_.StringArray'>
```

Would like your thoughts on how to either test this or put in types so that it knows whether `np.ndarray` or `ExtensionArray` are being returned.

**Comment by zkrolikowski-vl** [comment]
Thanks for letting us know about it @Dr-Irv.

This is revelation, albeit negative. There are three solutions with increasing grades of difficulty:

- Make the return type `Any` so not be restrictive. Requires consciously doing a `cast` otherwise users will lose type safety.
- Make the return type a union of all possible return types (I assume that the amount is finite). This will require a `cast` but the user will at least be forced to choose an appropriate type.
- Make `Series` a generic (I think that's already the case in Microsoft stubs) and prepare a number of overloads base on `dtype` in the class constructor. Each constructor will return a differently parametrized `Series` object which will be then returned by the `values` property. The same would have to be done to `astype`. This would theoretically work however I'm not sure that it wouldn't "trickle-down" to the users which would be forced to specify a type for each declaration of Series  - this isn't necessarily a bad thing but that's a huge leap in terms of the interface.

Short term I'll might prepare a fix with the first option in the spirit of "can't prove I'm wrong" and making the interface overly broad but true. 

Long term I might need to do a bit of research and trials.

Thanks for reaching out. It might take a while to find a systematic fix.

**Comment by Dr-Irv** [comment]
@zkrolikowski-vl 

I don't think the third option will work because even after you have constructed a `Series`, the type can change under the hood due to calculations.  E.g.:
```python
>>> import pandas as pd
>>> s = pd.Series([1,2,3])
>>> s
0    1
1    2
2    3
dtype: int64
>>> s.iloc[1] = 2.5
>>> s
0    1.0
1    2.5
2    3.0
dtype: float64
>>>
```
In pandas, the return type of `values` is `ArrayLike` which is defined as `ArrayLike = Union["ExtensionArray", np.ndarray]` in `_typing.pyi` and in the MS stubs, we are defining `values` to return `ArrayLike` , which is the second solution.

So I think we will go in that direction and change the tests you did accordingly.  I would suggest the second option.  For `values`, users have to do a `cast`
