### ISSUE TITLE
os.PathLike not compatible with pandas._typing.FilePathOrBuffer

### ISSUE THREAD

**Issue by headtr1ck** [VirtusLab/pandas-stubs#39]
This issue occurs when using `df.to_csv(some_path_like)` where `some_path_like` is typed as `os.PathLike`.

minimal example:
```
import os
import pandas as pd

def write(path: os.PathLike):
    df = pd.DataFrame()
    df.to_csv(path)
```

When using this, I get the mypy error: `error: Argument 1 to "to_csv" of "NDFrame" has incompatible type "_PathLike[Any]"; expected "Union[str, Path, IO[str], None]"`

You use `Optional[FilePathOrBuffer[AnyStr]]=...`, so I don't actually know if this is an issue of pandas._typing or if it could be fixed here or if it supposed to work like that.

**Comment by joannasendorek** [comment]
I checked with the pandas and it seems this part was changed - and our stubs had this outdated - https://github.com/pandas-dev/pandas/commit/c4c1dc3563ec95da1e700f96c9848be874699818

Following current typing from pandas, I changed our code: https://github.com/VirtusLab/pandas-stubs/pull/41/files 
This however will lead to changing your signature to:
```

def write(path: os.PathLike[Any]):
    df = pd.DataFrame()
    df.to_csv(path)
```
, because os.PathLike seems to be a generic type. Would it be okay for your case?

**Comment by headtr1ck** [comment]
Never realized that os.PathLike is generic. We will adopt to this.
Looks good to me :)
