### ISSUE TITLE
pd.DataFrame.eval returns pd.DataFrame

### ISSUE THREAD

**Issue by ivan-piskunov-cndt** [VirtusLab/pandas-stubs#79]
```python
df = pd.DataFrame({"a": [1, 2, 3]})
df.eval('b = a * 3')
Out[9]: 
   a  b
0  1  3
1  2  6
2  3  9
type(df.eval('b = a * 3'))
Out[10]: pandas.core.frame.DataFrame
```
As you can see above `pd.DataFrame.eval` also returns `pd.DataFrame`, [doc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.eval.html) is not so accurate in this case.

**Comment by joannasendorek** [comment]
Hi! Thanks for reporting, I will prepare fix for the issue.

**Comment by joannasendorek** [comment]
In this case, our definition for eval() is:

```
@overload
def eval(self, expr: str, inplace: Literal[False] = ..., **kwargs: Any) -> Union[np.ndarray, int, float, PandasObject]: ...
```

And DataFrame is subclass of PandasObject, so the annotation is correct. The problem here is that you get more general type, so if you need more specific one, you have to do the casting. For example:

df: DataFrame = cast(DataFrame, df.eval('b = a * 3'))

The same situation would occur if we extend Union[np.ndarray, int, float, PandasObject] with pd.DataFrame explicitly listed.

**Comment by zkrolikowski-vl** [comment]
In order for mypy to distinguish between options for the return type it would have to actually evaluate the expression which to best of my knowledge is impossible with type stubs.
 
Unfortunately in this case we stumbled onto a limitation of Python static type analysis.

**Comment by ivan-piskunov-cndt** [comment]
Makes sense! Thank you and sorry for the false-alarm

**Comment by joannasendorek** [comment]
No problem, it was interesting to check how things work.
